"""
Configuration constants for the Discord bot.
"""

EMBED_TITLE_MAX = 256
EMBED_DESCRIPTION_MAX = 4096
EMBED_FIELD_VALUE_MAX = 1024
EMBED_FIELD_NAME_MAX = 256
MESSAGE_CONTENT_MAX = 2000

COMMAND_PREFIX = '!'
PAGINATOR_TIMEOUT = 300
RATE_LIMIT_DELAY = 0.5

COLOR_SUCCESS = 0x00FF00
COLOR_ERROR = 0xFF0000
COLOR_WARNING = 0xFFA500
COLOR_INFO = 0x00B0F4

DEFAULT_NEWS_LIMIT = 5
MAX_NEWS_LIMIT = 10
MIN_NEWS_LIMIT = 1

ALLOWED_IMPLEMENT_USERS = None
ALLOWED_IMPLEMENT_ROLES = None
