"""
UI components for the Discord bot.
"""

import discord
from typing import List, Dict
from lib.config import EMBED_TITLE_MAX, EMBED_DESCRIPTION_MAX, EMBED_FIELD_VALUE_MAX, COLOR_INFO
from lib.utils import truncate_text, truncate_list_to_field


class IdeasPaginator(discord.ui.View):
    """Paginator view for browsing through AI-generated project ideas."""
    
    def __init__(self, ideas: List[Dict], author_id: int, timeout: int = 300):
        """
        Initialize the paginator.
        
        Args:
            ideas: List of idea dictionaries
            author_id: ID of the user who created this view
            timeout: View timeout in seconds (default: 300)
        """
        super().__init__(timeout=timeout)
        self.ideas = ideas
        self.current_page = 0
        self.total_pages = len(ideas)
        self.author_id = author_id

    async def get_page_embed(self) -> discord.Embed:
        """
        Generate embed for the current page.
        
        Returns:
            Discord embed for the current idea
        """
        idea = self.ideas[self.current_page]
        
        title = truncate_text(
            f"💡 Project {self.current_page + 1}/{self.total_pages}: {idea.get('title', 'Untitled')}",
            EMBED_TITLE_MAX
        )
        
        description = truncate_text(
            idea.get('description', 'No description available.'),
            EMBED_DESCRIPTION_MAX
        )
        
        embed = discord.Embed(
            title=title,
            description=description,
            color=COLOR_INFO
        )
        
        inspiration_link = idea.get('inspiration_link')
        if inspiration_link:
            embed.url = inspiration_link
        
        requirements = idea.get('requirements', [])
        if requirements:
            reqs_text = truncate_list_to_field(requirements, EMBED_FIELD_VALUE_MAX)
            embed.add_field(
                name="🛠️ Requirements",
                value=reqs_text,
                inline=False
            )
        
        functionalities = idea.get('functionalities', [])
        if functionalities:
            funcs_text = truncate_list_to_field(functionalities, EMBED_FIELD_VALUE_MAX)
            embed.add_field(
                name="⚙️ Functionalities",
                value=funcs_text,
                inline=False
            )
        
        embed.set_footer(
            text=f"Idea {self.current_page + 1} of {self.total_pages} | Generated by Gemini AI"
        )
        embed.timestamp = discord.utils.utcnow()
        
        return embed

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        """Check if the user is authorized to interact with this view."""
        if interaction.user.id != self.author_id:
            await interaction.response.send_message(
                "❌ You can't interact with someone else's command! Use the command yourself to interact.",
                ephemeral=True
            )
            return False
        return True

    @discord.ui.button(label="⬅️ Previous", style=discord.ButtonStyle.secondary, row=0)
    async def prev_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        """Navigate to previous page."""
        if self.current_page > 0:
            self.current_page -= 1
            embed = await self.get_page_embed()
            await interaction.response.edit_message(embed=embed, view=self)
        else:
            await interaction.response.defer()

    @discord.ui.button(label="➡️ Next", style=discord.ButtonStyle.secondary, row=0)
    async def next_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        """Navigate to next page."""
        if self.current_page < self.total_pages - 1:
            self.current_page += 1
            embed = await self.get_page_embed()
            await interaction.response.edit_message(embed=embed, view=self)
        else:
            await interaction.response.defer()

    @discord.ui.button(label="❌ Close", style=discord.ButtonStyle.danger, row=0)
    async def close_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        """Close the paginator."""
        self.stop()
        await interaction.response.edit_message(view=None)


class SavedIdeasPaginator(discord.ui.View):
    """Paginator view for browsing saved ideas from database with implementation status."""
    
    def __init__(self, ideas: List[Dict], author_id: int, allowed_user_ids: List[int] = None, timeout: int = 300):
        """
        Initialize the paginator.
        
        Args:
            ideas: List of saved idea dictionaries from database
            author_id: ID of the user who created this view
            allowed_user_ids: List of user IDs allowed to mark ideas as implemented (None = only author)
            timeout: View timeout in seconds (default: 300)
        """
        super().__init__(timeout=timeout)
        self.ideas = ideas
        self.current_page = 0
        self.total_pages = len(ideas)
        self.author_id = author_id
        self.allowed_user_ids = allowed_user_ids or [author_id]

    async def get_page_embed(self) -> discord.Embed:
        """
        Generate embed for the current page.
        
        Returns:
            Discord embed for the current idea
        """
        idea = self.ideas[self.current_page]
        idea_id = idea.get('id', '?')
        is_implemented = idea.get('implemented', False)
        
        status_icon = "✅" if is_implemented else "💡"
        title = truncate_text(
            f"{status_icon} Project {self.current_page + 1}/{self.total_pages}: {idea.get('title', 'Untitled')}",
            EMBED_TITLE_MAX
        )
        
        description = truncate_text(
            idea.get('description', 'No description available.'),
            EMBED_DESCRIPTION_MAX
        )
        
        color = 0x00FF00 if is_implemented else COLOR_INFO
        
        embed = discord.Embed(
            title=title,
            description=description,
            color=color
        )
        
        embed.add_field(name="🆔 ID", value=f"#{idea_id}", inline=True)
        
        status_text = "✅ Implemented" if is_implemented else "⏳ Not Implemented"
        if is_implemented and idea.get('implemented_at'):
            status_text += f"\n📅 {idea['implemented_at']}"
        embed.add_field(name="📊 Status", value=status_text, inline=True)
        
        inspiration_link = idea.get('inspiration_link')
        if inspiration_link:
            embed.url = inspiration_link
        
        requirements = idea.get('requirements', [])
        if requirements:
            reqs_text = truncate_list_to_field(requirements, EMBED_FIELD_VALUE_MAX)
            embed.add_field(
                name="🛠️ Requirements",
                value=reqs_text,
                inline=False
            )
        
        functionalities = idea.get('functionalities', [])
        if functionalities:
            funcs_text = truncate_list_to_field(functionalities, EMBED_FIELD_VALUE_MAX)
            embed.add_field(
                name="⚙️ Functionalities",
                value=funcs_text,
                inline=False
            )
        
        if idea.get('created_at'):
            embed.add_field(name="📅 Created", value=idea['created_at'], inline=False)
        
        embed.set_footer(
            text=f"Idea {self.current_page + 1} of {self.total_pages} | ID: #{idea_id}"
        )
        embed.timestamp = discord.utils.utcnow()
        
        return embed

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        """Check if the user is authorized to interact with this view."""
        return True

    @discord.ui.button(label="⬅️ Previous", style=discord.ButtonStyle.secondary, row=0)
    async def prev_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        """Navigate to previous page."""
        if self.current_page > 0:
            self.current_page -= 1
            embed = await self.get_page_embed()
            await interaction.response.edit_message(embed=embed, view=self)
        else:
            await interaction.response.defer()

    @discord.ui.button(label="➡️ Next", style=discord.ButtonStyle.secondary, row=0)
    async def next_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        """Navigate to next page."""
        if self.current_page < self.total_pages - 1:
            self.current_page += 1
            embed = await self.get_page_embed()
            await interaction.response.edit_message(embed=embed, view=self)
        else:
            await interaction.response.defer()

    @discord.ui.button(label="✅ Mark Implemented", style=discord.ButtonStyle.success, row=1)
    async def mark_implemented_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        """Mark current idea as implemented."""
        if interaction.user.id not in self.allowed_user_ids:
            await interaction.response.send_message(
                "❌ You don't have permission to mark ideas as implemented. Only authorized users can use this feature.",
                ephemeral=True
            )
            return
        
        idea = self.ideas[self.current_page]
        idea_id = idea.get('id')
        
        if not idea_id:
            await interaction.response.send_message("❌ Error: Idea ID not found.", ephemeral=True)
            return
        
        if idea.get('implemented'):
            await interaction.response.send_message("ℹ️ This idea is already marked as implemented.", ephemeral=True)
            return
        
        from lib.database import mark_idea_implemented, get_idea_by_id
        success = mark_idea_implemented(idea_id)
        
        if success:
            updated_idea = get_idea_by_id(idea_id)
            if updated_idea:
                self.ideas[self.current_page] = updated_idea
            
            embed = await self.get_page_embed()
            await interaction.response.edit_message(embed=embed, view=self)
        else:
            await interaction.response.send_message("❌ Error: Could not mark idea as implemented.", ephemeral=True)

    @discord.ui.button(label="❌ Close", style=discord.ButtonStyle.danger, row=1)
    async def close_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        """Close the paginator."""
        self.stop()
        await interaction.response.edit_message(view=None)
